// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorRunner
{
    using System.Linq;
    using System.Text;
    using TypescriptModel.Controller;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ControllerTemplate : BaseTextTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 5 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"

	public ControllerModel Model { get; set; }

	protected string GetMethodName(MethodModel methodModel)
    {
        var name = methodModel.Name.ToLower();
        switch (name)
        {
            case "get":
                return "getBy" + GetPascalCase(methodModel.Parameters.FirstOrDefault()?.Name);
            case "post":
                return "post" + GetPascalCase(methodModel.Parameters.FirstOrDefault()?.Name);
            case "put":
                var parameter = methodModel.Parameters.FirstOrDefault();
                if (methodModel.Parameters.Count > 1 && parameter?.Name.ToLower() == "id")
                    parameter = methodModel.Parameters[1];
                return "put" + GetPascalCase(parameter?.Name);
			default:
				return GetCamelCase(methodModel.Name);
        }
    }

    protected string BuildParams(MethodModel methodModel)
    {
        var sb = new StringBuilder();
        foreach (var parameterInfo in methodModel.Parameters)
        {
            sb.Append($"{parameterInfo.Name}: {parameterInfo.TsType}, ");
        }
        if (sb.Length > 0)
            sb.Remove(sb.Length - 2, 2);
        return sb.ToString();
    }
    protected string BuildCallParams(MethodModel methodModel)
    {
        var sb = new StringBuilder();
        foreach (var parameterInfo in methodModel.Parameters)
        {
            sb.Append($"{parameterInfo.Name}, ");
        }
        if (sb.Length > 0)
            sb.Remove(sb.Length - 2, 2);
        return sb.ToString();
    }

    protected string FixRouteParameters(string route)
    {
        var result = "'" + route.Replace("{", "' + ").Replace("}", " + '");
        if (result.EndsWith(" + '"))
            result = result.Substring(0, result.Length - 3);
        else
            result = result + "'";
        return result;
    }

	protected string GetUrlAdjust(ParameterModel p)
	{
		return p.IsComplex
			? $"this._addParam({p.Name});"
			: $"'{p.Name}=' + this._encode({p.Name}) + '&';";
	}

    protected void WriteUrlBuilder()
    { 
        
        #line default
        #line hidden
        
        #line 68 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("    urlBuilder = {\r\n");

        
        #line default
        #line hidden
        
        #line 70 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
 foreach (var method in Model.Methods) {
        
        #line default
        #line hidden
        
        #line 70 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 71 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodName(method)));

        
        #line default
        #line hidden
        
        #line 71 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 71 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(BuildParams(method)));

        
        #line default
        #line hidden
        
        #line 71 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(") {\r\n            var url = ");

        
        #line default
        #line hidden
        
        #line 72 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(FixRouteParameters(method.Route)));

        
        #line default
        #line hidden
        
        #line 72 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(";\r\n            var params = \'\';\r\n");

        
        #line default
        #line hidden
        
        #line 74 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
 foreach (var p in method.Parameters.Where(prm => prm.ParameterType == ParameterType.QueryString)) {
        
        #line default
        #line hidden
        
        #line 74 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("            params = params + ");

        
        #line default
        #line hidden
        
        #line 75 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GetUrlAdjust(p)));

        
        #line default
        #line hidden
        
        #line 75 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 76 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 76 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("            return this._getUrl(url, params);\r\n        },\r\n");

        
        #line default
        #line hidden
        
        #line 79 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 79 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write("\r\n        _domain: Global.host + Global.");

        
        #line default
        #line hidden
        
        #line 81 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Model.Module));

        
        #line default
        #line hidden
        
        #line 81 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
this.Write(@",
        _addParam(p: any) {
            var result = '';
            if (p) {
                for (var propertyName in p) {
                    if (p[propertyName] && !(p[propertyName] instanceof Function) && ((p[propertyName] != ''))) {
                        result = result + propertyName + '=' + this._encode(p[propertyName]) + '&';
                    }
                }
            }
            return result;
        },
        _encode(p: any) {
            if (p instanceof Date) {
				var month = p.getMonth() + 1;
				month = month <= 9 ? '0' + month : month;
				var day = p.getDate();
				day = day <= 9 ? '0' + day : day;
                return p.getFullYear() + '-' + month + '-' + day;
			} else {
                return encodeURIComponent(p);
			}
        },
        _getUrl(baseUrl: string, params: string) {
            var result = this._domain + '/' + baseUrl
            if (params.length > 0) {
                result = result + '?' + params.slice(0, -1);
            }
            return result;
        }
    }
        
");

        
        #line default
        #line hidden
        
        #line 113 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ControllerTemplate.tt"
    
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
