// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorRunner
{
    using TypescriptModel.Poco;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ModelTemplate : BaseTextTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
 ImportUsedClasses(Model.UsedClasses, Model.Module); 
            
            #line default
            #line hidden
            this.Write("export class ");
            
            #line 4 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.TsName));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 5 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
 foreach (var property in Model.Properties) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 6 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 6 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ClassName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 7 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 9 "C:\src\Credfi\Deploy\Tools\TypescriptGenerator\GeneratorRunner\ModelTemplate.tt"
 public ClassModel Model { get; set; } 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
